# Site settings
title: "Architectural Robotics"
email: jverissi@hawk.iit.edu
description: "A blog about the application of robots in achitecture"
baseurl: ""
url: "http://yulion21.github.io/"
title_description: "A blog about the application of robots in achitecture"
title_image: "https://scontent.xx.fbcdn.net/v/t1.0-9/13245470_923724344391619_5758275307298915441_n.jpg?oh=b1ae0110943a0afa891b846a1f6a566b&oe=57D8A27C"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
